/**
 * Merchant knowledge base — the cold-start half of the categoriser.
 *
 * A brand-new account has no labelled history, so the Naive Bayes model has
 * nothing to learn from. This lexicon gives a sensible answer on the very first
 * import; the model then takes over as the user confirms and corrects
 * categories. Keys are lowercase substrings matched against the normalised
 * description. Longer keys win, so "amazon prime" beats "amazon".
 */

export const MERCHANT_LEXICON: Record<string, string> = {
  /* ── Groceries ───────────────────────────────────────────── */
  tesco: "Groceries",
  sainsbury: "Groceries",
  asda: "Groceries",
  morrisons: "Groceries",
  aldi: "Groceries",
  lidl: "Groceries",
  waitrose: "Groceries",
  "marks & spencer food": "Groceries",
  "co-op": "Groceries",
  coop: "Groceries",
  iceland: "Groceries",
  ocado: "Groceries",
  budgens: "Groceries",
  spar: "Groceries",
  costcutter: "Groceries",
  "whole foods": "Groceries",
  "trader joe": "Groceries",
  kroger: "Groceries",
  safeway: "Groceries",
  walmart: "Groceries",
  costco: "Groceries",
  carrefour: "Groceries",
  "holland & barrett": "Groceries",

  /* ── Eating out ──────────────────────────────────────────── */
  mcdonald: "Eating Out",
  "burger king": "Eating Out",
  kfc: "Eating Out",
  subway: "Eating Out",
  greggs: "Eating Out",
  pret: "Eating Out",
  "pret a manger": "Eating Out",
  starbucks: "Eating Out",
  costa: "Eating Out",
  caffe: "Eating Out",
  "coffee": "Eating Out",
  nero: "Eating Out",
  nandos: "Eating Out",
  "nando's": "Eating Out",
  wagamama: "Eating Out",
  "pizza express": "Eating Out",
  dominos: "Eating Out",
  "domino's": "Eating Out",
  "papa john": "Eating Out",
  "pizza hut": "Eating Out",
  deliveroo: "Eating Out",
  "just eat": "Eating Out",
  ubereats: "Eating Out",
  "uber eats": "Eating Out",
  doordash: "Eating Out",
  grubhub: "Eating Out",
  itsu: "Eating Out",
  leon: "Eating Out",
  "five guys": "Eating Out",
  chipotle: "Eating Out",
  "shake shack": "Eating Out",
  wetherspoon: "Eating Out",
  "the ivy": "Eating Out",
  restaurant: "Eating Out",
  bistro: "Eating Out",
  brewery: "Eating Out",
  "bar ": "Eating Out",
  pub: "Eating Out",
  tavern: "Eating Out",
  kitchen: "Eating Out",
  grill: "Eating Out",
  bakery: "Eating Out",
  deli: "Eating Out",

  /* ── Rent & mortgage ─────────────────────────────────────── */
  rent: "Rent & Mortgage",
  landlord: "Rent & Mortgage",
  mortgage: "Rent & Mortgage",
  "letting": "Rent & Mortgage",
  "property management": "Rent & Mortgage",
  "housing assoc": "Rent & Mortgage",
  "council tenancy": "Rent & Mortgage",

  /* ── Bills & utilities ───────────────────────────────────── */
  "british gas": "Bills & Utilities",
  "octopus energy": "Bills & Utilities",
  "e.on": "Bills & Utilities",
  eon: "Bills & Utilities",
  edf: "Bills & Utilities",
  ovo: "Bills & Utilities",
  "scottish power": "Bills & Utilities",
  "bulb energy": "Bills & Utilities",
  "shell energy": "Bills & Utilities",
  "thames water": "Bills & Utilities",
  "severn trent": "Bills & Utilities",
  "anglian water": "Bills & Utilities",
  "yorkshire water": "Bills & Utilities",
  water: "Bills & Utilities",
  "council tax": "Bills & Utilities",
  "tv licence": "Bills & Utilities",
  "tv license": "Bills & Utilities",
  "virgin media": "Bills & Utilities",
  "sky digital": "Bills & Utilities",
  "sky uk": "Bills & Utilities",
  "bt group": "Bills & Utilities",
  "bt broadband": "Bills & Utilities",
  talktalk: "Bills & Utilities",
  plusnet: "Bills & Utilities",
  hyperoptic: "Bills & Utilities",
  vodafone: "Bills & Utilities",
  "ee limited": "Bills & Utilities",
  o2: "Bills & Utilities",
  three: "Bills & Utilities",
  giffgaff: "Bills & Utilities",
  "id mobile": "Bills & Utilities",
  verizon: "Bills & Utilities",
  "at&t": "Bills & Utilities",
  comcast: "Bills & Utilities",
  electric: "Bills & Utilities",
  "gas bill": "Bills & Utilities",
  broadband: "Bills & Utilities",

  /* ── Transport ───────────────────────────────────────────── */
  tfl: "Transport",
  "transport for london": "Transport",
  "oyster": "Transport",
  "national rail": "Transport",
  trainline: "Transport",
  "lner": "Transport",
  "gwr": "Transport",
  "southern rail": "Transport",
  "thameslink": "Transport",
  "avanti": "Transport",
  "cross country": "Transport",
  uber: "Transport",
  bolt: "Transport",
  lyft: "Transport",
  "free now": "Transport",
  taxi: "Transport",
  cab: "Transport",
  "national express": "Transport",
  megabus: "Transport",
  stagecoach: "Transport",
  "first bus": "Transport",
  arriva: "Transport",
  "car park": "Transport",
  parking: "Transport",
  ringgo: "Transport",
  "justpark": "Transport",
  "congestion charge": "Transport",
  dvla: "Transport",
  mot: "Transport",
  "kwik fit": "Transport",
  halfords: "Transport",
  "zipcar": "Transport",
  lime: "Transport",

  /* ── Fuel ────────────────────────────────────────────────── */
  shell: "Fuel",
  bp: "Fuel",
  esso: "Fuel",
  texaco: "Fuel",
  gulf: "Fuel",
  "petrol": "Fuel",
  "fuel": "Fuel",
  "service station": "Fuel",
  chevron: "Fuel",
  exxon: "Fuel",

  /* ── Shopping ────────────────────────────────────────────── */
  amazon: "Shopping",
  ebay: "Shopping",
  etsy: "Shopping",
  argos: "Shopping",
  "john lewis": "Shopping",
  "marks & spencer": "Shopping",
  "m&s": "Shopping",
  next: "Shopping",
  primark: "Shopping",
  zara: "Shopping",
  "h&m": "Shopping",
  uniqlo: "Shopping",
  asos: "Shopping",
  boohoo: "Shopping",
  shein: "Shopping",
  vinted: "Shopping",
  depop: "Shopping",
  tkmaxx: "Shopping",
  "tk maxx": "Shopping",
  "sports direct": "Shopping",
  jd_sports: "Shopping",
  "jd sports": "Shopping",
  nike: "Shopping",
  adidas: "Shopping",
  "apple store": "Shopping",
  currys: "Shopping",
  "pc world": "Shopping",
  screwfix: "Shopping",
  "b&q": "Shopping",
  wickes: "Shopping",
  ikea: "Shopping",
  dunelm: "Shopping",
  wilko: "Shopping",
  "the range": "Shopping",
  aliexpress: "Shopping",
  temu: "Shopping",
  target: "Shopping",
  "best buy": "Shopping",

  /* ── Subscriptions ───────────────────────────────────────── */
  netflix: "Subscriptions",
  spotify: "Subscriptions",
  "disney+": "Subscriptions",
  "disney plus": "Subscriptions",
  "amazon prime": "Subscriptions",
  "prime video": "Subscriptions",
  "apple music": "Subscriptions",
  "apple tv": "Subscriptions",
  "apple.com/bill": "Subscriptions",
  icloud: "Subscriptions",
  "google storage": "Subscriptions",
  "google one": "Subscriptions",
  youtube: "Subscriptions",
  "now tv": "Subscriptions",
  nowtv: "Subscriptions",
  hulu: "Subscriptions",
  "hbo max": "Subscriptions",
  paramount: "Subscriptions",
  audible: "Subscriptions",
  kindle: "Subscriptions",
  patreon: "Subscriptions",
  substack: "Subscriptions",
  medium: "Subscriptions",
  dropbox: "Subscriptions",
  notion: "Subscriptions",
  figma: "Subscriptions",
  adobe: "Subscriptions",
  microsoft: "Subscriptions",
  "office 365": "Subscriptions",
  github: "Subscriptions",
  openai: "Subscriptions",
  anthropic: "Subscriptions",
  "claude.ai": "Subscriptions",
  duolingo: "Subscriptions",
  strava: "Subscriptions",
  linkedin: "Subscriptions",
  canva: "Subscriptions",
  "playstation": "Subscriptions",
  "xbox": "Subscriptions",
  nintendo: "Subscriptions",
  steam: "Entertainment",

  /* ── Health & fitness ────────────────────────────────────── */
  boots: "Health & Fitness",
  superdrug: "Health & Fitness",
  pharmacy: "Health & Fitness",
  "puregym": "Health & Fitness",
  "the gym group": "Health & Fitness",
  "david lloyd": "Health & Fitness",
  "virgin active": "Health & Fitness",
  "nuffield health": "Health & Fitness",
  gym: "Health & Fitness",
  fitness: "Health & Fitness",
  dentist: "Health & Fitness",
  dental: "Health & Fitness",
  optician: "Health & Fitness",
  specsavers: "Health & Fitness",
  "vision express": "Health & Fitness",
  bupa: "Health & Fitness",
  nhs: "Health & Fitness",
  physio: "Health & Fitness",
  clinic: "Health & Fitness",

  /* ── Entertainment ───────────────────────────────────────── */
  cineworld: "Entertainment",
  odeon: "Entertainment",
  vue: "Entertainment",
  picturehouse: "Entertainment",
  cinema: "Entertainment",
  ticketmaster: "Entertainment",
  eventbrite: "Entertainment",
  dice: "Entertainment",
  "see tickets": "Entertainment",
  theatre: "Entertainment",
  "national trust": "Entertainment",
  "english heritage": "Entertainment",
  museum: "Entertainment",
  bowling: "Entertainment",
  golf: "Entertainment",

  /* ── Travel ──────────────────────────────────────────────── */
  ryanair: "Travel",
  easyjet: "Travel",
  "british airways": "Travel",
  jet2: "Travel",
  wizz: "Travel",
  tui: "Travel",
  emirates: "Travel",
  lufthansa: "Travel",
  klm: "Travel",
  "booking.com": "Travel",
  airbnb: "Travel",
  hotels: "Travel",
  expedia: "Travel",
  premier_inn: "Travel",
  "premier inn": "Travel",
  travelodge: "Travel",
  hilton: "Travel",
  marriott: "Travel",
  eurostar: "Travel",
  hostel: "Travel",
  airport: "Travel",

  /* ── Personal care ───────────────────────────────────────── */
  barber: "Personal Care",
  "hair": "Personal Care",
  salon: "Personal Care",
  spa: "Personal Care",
  "the body shop": "Personal Care",
  lush: "Personal Care",
  sephora: "Personal Care",
  "space nk": "Personal Care",

  /* ── Home & garden ───────────────────────────────────────── */
  "homebase": "Home & Garden",
  "garden centre": "Home & Garden",
  furniture: "Home & Garden",
  "dfs": "Home & Garden",
  "made.com": "Home & Garden",

  /* ── Insurance ───────────────────────────────────────────── */
  insurance: "Insurance",
  "admiral": "Insurance",
  "aviva": "Insurance",
  "direct line": "Insurance",
  "churchill": "Insurance",
  "hastings": "Insurance",
  "lv=": "Insurance",
  axa: "Insurance",
  "legal & general": "Insurance",

  /* ── Education ───────────────────────────────────────────── */
  "student loan": "Education",
  university: "Education",
  college: "Education",
  udemy: "Education",
  coursera: "Education",
  "waterstones": "Education",
  "book depository": "Education",

  /* ── Pets ────────────────────────────────────────────────── */
  "pets at home": "Pets",
  petco: "Pets",
  vet: "Pets",
  veterinary: "Pets",

  /* ── Kids & family ───────────────────────────────────────── */
  nursery: "Kids & Family",
  childcare: "Kids & Family",
  "smyths": "Kids & Family",
  "the entertainer": "Kids & Family",

  /* ── Gifts & donations ───────────────────────────────────── */
  charity: "Gifts & Donations",
  oxfam: "Gifts & Donations",
  "cancer research": "Gifts & Donations",
  "red cross": "Gifts & Donations",
  unicef: "Gifts & Donations",
  justgiving: "Gifts & Donations",
  gofundme: "Gifts & Donations",
  donation: "Gifts & Donations",

  /* ── Fees & taxes ────────────────────────────────────────── */
  "overdraft fee": "Fees & Charges",
  "interest charge": "Fees & Charges",
  "non-sterling": "Fees & Charges",
  "service charge": "Fees & Charges",
  "annual fee": "Fees & Charges",
  hmrc: "Taxes",
  "self assessment": "Taxes",
  "irs ": "Taxes",

  /* ── Cash ────────────────────────────────────────────────── */
  "cash withdrawal": "Cash & ATM",
  atm: "Cash & ATM",
  "link atm": "Cash & ATM",
  "cash machine": "Cash & ATM",

  /* ── Income ──────────────────────────────────────────────── */
  salary: "Salary",
  payroll: "Salary",
  wages: "Salary",
  "net pay": "Salary",
  bacs: "Salary",
  "hmrc rebate": "Refunds",
  refund: "Refunds",
  reimbursement: "Refunds",
  dividend: "Interest & Dividends",
  "interest paid": "Interest & Dividends",
  "gross interest": "Interest & Dividends",
  "child benefit": "Benefits",
  "universal credit": "Benefits",
  "state pension": "Benefits",

  /* ── Transfers ───────────────────────────────────────────── */
  "transfer to": "Transfers",
  "transfer from": "Transfers",
  "internal transfer": "Transfers",
  "standing order": "Transfers",
  "faster payment": "Transfers",
  monzo: "Transfers",
  revolut: "Transfers",
  starling: "Transfers",
  wise: "Transfers",
  paypal: "Shopping",
  "moneybox": "Savings",
  "chip savings": "Savings",
  "premium bonds": "Savings",
  "ns&i": "Savings",
  "savings pot": "Savings",
  "vanguard": "Investments",
  "hargreaves": "Investments",
  "trading 212": "Investments",
  freetrade: "Investments",
  "interactive investor": "Investments",
  coinbase: "Investments",
  binance: "Investments",
  etoro: "Investments",
  "credit card payment": "Credit Card Payment",
  "cc payment": "Credit Card Payment",
  "amex payment": "Credit Card Payment",
};

/** Keys sorted longest-first so the most specific brand match wins. */
export const LEXICON_KEYS = Object.keys(MERCHANT_LEXICON).sort((a, b) => b.length - a.length);

/**
 * Pretty display names for merchants whose normalised key is ugly or truncated.
 * Used by the recurring-payments view so the UI reads "Netflix", not "netflix com".
 */
export const DISPLAY_NAMES: Record<string, string> = {
  "amazon prime": "Amazon Prime",
  "apple com bill": "Apple",
  "pret a manger": "Pret A Manger",
  tfl: "TfL",
  "sainsburys": "Sainsbury's",
  "mcdonalds": "McDonald's",
  "nandos": "Nando's",
  "hmrc": "HMRC",
  "ee": "EE",
  "o2": "O2",
  "bp": "BP",
  "ns i": "NS&I",
};
